services:
  thymeleafcrud:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: thymeleafcrud
    environment:
      - PORT=8090
      - DB_URL=host.docker.internal
      - DB_USER=sa
      - DB_PASSWORD=your_password123
    ports:
      - 8090:8090
    network_mode: multiapp-network