apiVersion: v1
kind: Service
metadata:
  name: thymeleafcrud-service
  labels:
    appgroup: spring
spec:
  selector:
    app: thymeleafcrud
  type: LoadBalancer
  ports:
    - protocol: 'TCP'
      port: 8090
      targetPort: 8090