services:
  azuresqledge:
    image: mcr.microsoft.com/azure-sql-edge:latest
    cap_add:
      - SYS_PTRACE
    environment:
      - '''ACCEPT_EULA=1'''
      - '''MSSQL_SA_PASSWORD=your_password123'''
      - '''MSSQL_PID=Premium'''
    container_name: azuresqledge
    ports:
      - 1433:1433